---
abstract: 'An ORM for the published CPAN Testers SQLite database'
author:
  - 'Adam Kennedy'
build_requires:
  LWP::Online: 1.07
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: ORDB::CPANTesters
name: ORDB-CPANTesters
no_index:
  directory:
    - inc
    - t
requires:
  ORLite::Mirror: 1.12
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
